"""Domain-neutral file data foundation."""

from .record import (
    DuplicateRecordError,
    RecordValidationError,
    UnsafePathError,
    atomic_write_record,
    build_record,
    compute_content_hash,
    decode_record,
    encode_record,
    read_record,
    resolve_project_path,
    validate_record,
)
from .store import (
    APPROVED_RECORD_TYPES,
    APPROVED_STREAMS,
    EMPTY_STREAM_HASH,
    ConcurrentWriteError,
    ConflictError,
    ExpectationMismatchError,
    InputContractError,
    RecordIOError,
    RecordNotFoundError,
    RecordStore,
    StoreNotInitializedError,
    decode_stream,
    stream_content_hash,
)

__all__ = [
    "DuplicateRecordError",
    "RecordValidationError",
    "UnsafePathError",
    "atomic_write_record",
    "build_record",
    "compute_content_hash",
    "decode_record",
    "encode_record",
    "read_record",
    "resolve_project_path",
    "validate_record",
    "APPROVED_RECORD_TYPES",
    "APPROVED_STREAMS",
    "EMPTY_STREAM_HASH",
    "ConcurrentWriteError",
    "ConflictError",
    "ExpectationMismatchError",
    "InputContractError",
    "RecordIOError",
    "RecordNotFoundError",
    "RecordStore",
    "StoreNotInitializedError",
    "decode_stream",
    "stream_content_hash",
]
